name: Publish Docker on PR
on: 
  push:
    pull_request:
      branches:
        - master
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Publish to Registry
      uses: flaconi/Publish-Docker-Github-Action@master
      with:
        name: flaconi/atlantis-terragrunt:${{ github.sha }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
