name: Publish Docker
on:
  push: {}
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-publish:
    name:  "[ ${{ matrix.TF_VERSION }}-${{ matrix.TG_VERSION }} ]"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        TF_VERSION: [0.12.29,latest]
        TG_VERSION: [0.21.7, latest]
        exclude:
          - { TF_VERSION: latest, TG_VERSION: 0.21.7 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Variables
        id: vars
        run:  |
          d=$(date +%Y-%m-%d)
          tag=$d-${{ matrix.TF_VERSION }}-${{ matrix.TG_VERSION }}
          echo ::set-env name=TAG::${tag}
        #$(echo ${{ matrix.TF_VERSION }}-${{ matrix.TG_VERSION }})
        # with:
        #   ref: ${{ github.ref }}
      - name: Build an Publish
        run: |
          make build TF_VERSION=${{ matrix.TF_VERSION }} TG_VERSION=${{ matrix.TG_VERSION }}


        # make tag TAG=${{ env.TAG }}
        # make login DOCKER_USER=${{ secrets.DOCKER_USERNAME }} DOCKER_PASS=${{ secrets.DOCKER_PASSWORD }}
        # make push TAG=${{ env.TAG }}

      # - name: Publish to Registry
      #   uses: docker/build-push-action@v1
      #   with:
      #     name: runderwood/atlantis-terragrunt
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     build_args: DEFAULT_TERRAFORM_VERSION=${{ matrix.TF_VERSION }},TERRAGRUNT_VERSION=${{ matrix.TG_VERSION }}
      #     tags: "latest, ${{ env.RELEASE_VERSION }}"

      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: runderwood/atlantis-terragrunt
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     tag_semver: true
      #     tags: "latest, ${{ env.RELEASE_VERSION }}"
