name: Publish Docker
on:
  push: {}
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        version:
          - '0.14.0'
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: flaconi/atlantis-terragrunt
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
        tags: "latest,${{ matrix.version }}"
