name: Publish Docker
on:
  push: {}
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: False
      matrix:
        TF: [0.12, latest]
        TG: [0.21, 0.22, 0.23, latest]
        exclude:
          - { TF: latest, TG: 0.21 }
          - { TF: latest, TG: 0.22 }
          - { TF: latest, TG: 0.23 }
          - { TF: latest, TG: latest}
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${{ matrix.TF }}-${{ matrix.TG }})
        # with:
        #   ref: ${{ github.ref }}
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: runderwood/atlantis-terragrunt
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
          tags: "latest"
          #,${{ env.RELEASE_VERSION }}"
